#!/usr/bin/env python3
"""
Hyperliquid market configuration for Python clients.
Updated with architect-style symbology: EXCHANGE-BASE/QUOTE-TYPE
Total active markets: 172
"""

# Market symbol to ID mapping (full architect format)
MARKET_IDS = {
    "HYPERLIQUID-BTC/USD-PERP": 0,
    "HYPERLIQUID-ETH/USD-PERP": 1,
    "HYPERLIQUID-ATOM/USD-PERP": 2,
    "HYPERLIQUID-DYDX/USD-PERP": 4,
    "HYPERLIQUID-SOL/USD-PERP": 5,
    "HYPERLIQUID-AVAX/USD-PERP": 6,
    "HYPERLIQUID-BNB/USD-PERP": 7,
    "HYPERLIQUID-APE/USD-PERP": 8,
    "HYPERLIQUID-OP/USD-PERP": 9,
    "HYPERLIQUID-LTC/USD-PERP": 10,
    "HYPERLIQUID-ARB/USD-PERP": 11,
    "HYPERLIQUID-DOGE/USD-PERP": 12,
    "HYPERLIQUID-INJ/USD-PERP": 13,
    "HYPERLIQUID-SUI/USD-PERP": 14,
    "HYPERLIQUID-kPEPE/USD-PERP": 15,
    "HYPERLIQUID-CRV/USD-PERP": 16,
    "HYPERLIQUID-LDO/USD-PERP": 17,
    "HYPERLIQUID-LINK/USD-PERP": 18,
    "HYPERLIQUID-STX/USD-PERP": 19,
    "HYPERLIQUID-CFX/USD-PERP": 21,
    "HYPERLIQUID-GMX/USD-PERP": 23,
    "HYPERLIQUID-SNX/USD-PERP": 24,
    "HYPERLIQUID-XRP/USD-PERP": 25,
    "HYPERLIQUID-BCH/USD-PERP": 26,
    "HYPERLIQUID-APT/USD-PERP": 27,
    "HYPERLIQUID-AAVE/USD-PERP": 28,
    "HYPERLIQUID-COMP/USD-PERP": 29,
    "HYPERLIQUID-MKR/USD-PERP": 30,
    "HYPERLIQUID-WLD/USD-PERP": 31,
    "HYPERLIQUID-FXS/USD-PERP": 32,
    "HYPERLIQUID-YGG/USD-PERP": 36,
    "HYPERLIQUID-TRX/USD-PERP": 37,
    "HYPERLIQUID-kSHIB/USD-PERP": 38,
    "HYPERLIQUID-UNI/USD-PERP": 39,
    "HYPERLIQUID-SEI/USD-PERP": 40,
    "HYPERLIQUID-RUNE/USD-PERP": 41,
    "HYPERLIQUID-ZRO/USD-PERP": 46,
    "HYPERLIQUID-DOT/USD-PERP": 48,
    "HYPERLIQUID-BANANA/USD-PERP": 49,
    "HYPERLIQUID-TRB/USD-PERP": 50,
    "HYPERLIQUID-FTT/USD-PERP": 51,
    "HYPERLIQUID-OGN/USD-PERP": 53,
    "HYPERLIQUID-ARK/USD-PERP": 55,
    "HYPERLIQUID-REQ/USD-PERP": 58,
    "HYPERLIQUID-BIGTIME/USD-PERP": 59,
    "HYPERLIQUID-KAS/USD-PERP": 60,
    "HYPERLIQUID-BLUR/USD-PERP": 62,
    "HYPERLIQUID-TIA/USD-PERP": 63,
    "HYPERLIQUID-BSV/USD-PERP": 64,
    "HYPERLIQUID-ADA/USD-PERP": 65,
    "HYPERLIQUID-TON/USD-PERP": 66,
    "HYPERLIQUID-MINA/USD-PERP": 67,
    "HYPERLIQUID-POLYX/USD-PERP": 68,
    "HYPERLIQUID-GAS/USD-PERP": 69,
    "HYPERLIQUID-PENDLE/USD-PERP": 70,
    "HYPERLIQUID-STG/USD-PERP": 71,
    "HYPERLIQUID-FET/USD-PERP": 72,
    "HYPERLIQUID-NEAR/USD-PERP": 74,
    "HYPERLIQUID-MEME/USD-PERP": 75,
    "HYPERLIQUID-ORDI/USD-PERP": 76,
    "HYPERLIQUID-NEO/USD-PERP": 78,
    "HYPERLIQUID-ZEN/USD-PERP": 79,
    "HYPERLIQUID-FIL/USD-PERP": 80,
    "HYPERLIQUID-PYTH/USD-PERP": 81,
    "HYPERLIQUID-SUSHI/USD-PERP": 82,
    "HYPERLIQUID-IMX/USD-PERP": 84,
    "HYPERLIQUID-kBONK/USD-PERP": 85,
    "HYPERLIQUID-GMT/USD-PERP": 86,
    "HYPERLIQUID-SUPER/USD-PERP": 87,
    "HYPERLIQUID-USTC/USD-PERP": 88,
    "HYPERLIQUID-JUP/USD-PERP": 90,
    "HYPERLIQUID-kLUNC/USD-PERP": 91,
    "HYPERLIQUID-RSR/USD-PERP": 92,
    "HYPERLIQUID-GALA/USD-PERP": 93,
    "HYPERLIQUID-JTO/USD-PERP": 94,
    "HYPERLIQUID-ACE/USD-PERP": 96,
    "HYPERLIQUID-MAV/USD-PERP": 97,
    "HYPERLIQUID-WIF/USD-PERP": 98,
    "HYPERLIQUID-CAKE/USD-PERP": 99,
    "HYPERLIQUID-PEOPLE/USD-PERP": 100,
    "HYPERLIQUID-ENS/USD-PERP": 101,
    "HYPERLIQUID-ETC/USD-PERP": 102,
    "HYPERLIQUID-XAI/USD-PERP": 103,
    "HYPERLIQUID-MANTA/USD-PERP": 104,
    "HYPERLIQUID-UMA/USD-PERP": 105,
    "HYPERLIQUID-ONDO/USD-PERP": 106,
    "HYPERLIQUID-ALT/USD-PERP": 107,
    "HYPERLIQUID-ZETA/USD-PERP": 108,
    "HYPERLIQUID-DYM/USD-PERP": 109,
    "HYPERLIQUID-MAVIA/USD-PERP": 110,
    "HYPERLIQUID-W/USD-PERP": 111,
    "HYPERLIQUID-STRK/USD-PERP": 113,
    "HYPERLIQUID-TAO/USD-PERP": 116,
    "HYPERLIQUID-AR/USD-PERP": 117,
    "HYPERLIQUID-kFLOKI/USD-PERP": 119,
    "HYPERLIQUID-BOME/USD-PERP": 120,
    "HYPERLIQUID-ETHFI/USD-PERP": 121,
    "HYPERLIQUID-ENA/USD-PERP": 122,
    "HYPERLIQUID-MNT/USD-PERP": 123,
    "HYPERLIQUID-TNSR/USD-PERP": 124,
    "HYPERLIQUID-SAGA/USD-PERP": 125,
    "HYPERLIQUID-MERL/USD-PERP": 126,
    "HYPERLIQUID-HBAR/USD-PERP": 127,
    "HYPERLIQUID-POPCAT/USD-PERP": 128,
    "HYPERLIQUID-OMNI/USD-PERP": 129,
    "HYPERLIQUID-EIGEN/USD-PERP": 130,
    "HYPERLIQUID-REZ/USD-PERP": 131,
    "HYPERLIQUID-NOT/USD-PERP": 132,
    "HYPERLIQUID-TURBO/USD-PERP": 133,
    "HYPERLIQUID-BRETT/USD-PERP": 134,
    "HYPERLIQUID-IO/USD-PERP": 135,
    "HYPERLIQUID-ZK/USD-PERP": 136,
    "HYPERLIQUID-BLAST/USD-PERP": 137,
    "HYPERLIQUID-MEW/USD-PERP": 139,
    "HYPERLIQUID-RENDER/USD-PERP": 140,
    "HYPERLIQUID-kDOGS/USD-PERP": 141,
    "HYPERLIQUID-POL/USD-PERP": 142,
    "HYPERLIQUID-CELO/USD-PERP": 144,
    "HYPERLIQUID-HMSTR/USD-PERP": 145,
    "HYPERLIQUID-SCR/USD-PERP": 146,
    "HYPERLIQUID-NEIROETH/USD-PERP": 147,
    "HYPERLIQUID-kNEIRO/USD-PERP": 148,
    "HYPERLIQUID-GOAT/USD-PERP": 149,
    "HYPERLIQUID-MOODENG/USD-PERP": 150,
    "HYPERLIQUID-GRASS/USD-PERP": 151,
    "HYPERLIQUID-PURR/USD-PERP": 152,
    "HYPERLIQUID-PNUT/USD-PERP": 153,
    "HYPERLIQUID-XLM/USD-PERP": 154,
    "HYPERLIQUID-CHILLGUY/USD-PERP": 155,
    "HYPERLIQUID-SAND/USD-PERP": 156,
    "HYPERLIQUID-IOTA/USD-PERP": 157,
    "HYPERLIQUID-ALGO/USD-PERP": 158,
    "HYPERLIQUID-HYPE/USD-PERP": 159,
    "HYPERLIQUID-ME/USD-PERP": 160,
    "HYPERLIQUID-MOVE/USD-PERP": 161,
    "HYPERLIQUID-VIRTUAL/USD-PERP": 162,
    "HYPERLIQUID-PENGU/USD-PERP": 163,
    "HYPERLIQUID-USUAL/USD-PERP": 164,
    "HYPERLIQUID-FARTCOIN/USD-PERP": 165,
    "HYPERLIQUID-AI16Z/USD-PERP": 166,
    "HYPERLIQUID-AIXBT/USD-PERP": 167,
    "HYPERLIQUID-ZEREBRO/USD-PERP": 168,
    "HYPERLIQUID-BIO/USD-PERP": 169,
    "HYPERLIQUID-GRIFFAIN/USD-PERP": 170,
    "HYPERLIQUID-SPX/USD-PERP": 171,
    "HYPERLIQUID-S/USD-PERP": 172,
    "HYPERLIQUID-MORPHO/USD-PERP": 173,
    "HYPERLIQUID-TRUMP/USD-PERP": 174,
    "HYPERLIQUID-MELANIA/USD-PERP": 175,
    "HYPERLIQUID-ANIME/USD-PERP": 176,
    "HYPERLIQUID-VINE/USD-PERP": 177,
    "HYPERLIQUID-VVV/USD-PERP": 178,
    "HYPERLIQUID-BERA/USD-PERP": 180,
    "HYPERLIQUID-TST/USD-PERP": 181,
    "HYPERLIQUID-LAYER/USD-PERP": 182,
    "HYPERLIQUID-IP/USD-PERP": 183,
    "HYPERLIQUID-OM/USD-PERP": 184,
    "HYPERLIQUID-KAITO/USD-PERP": 185,
    "HYPERLIQUID-NIL/USD-PERP": 186,
    "HYPERLIQUID-PAXG/USD-PERP": 187,
    "HYPERLIQUID-PROMPT/USD-PERP": 188,
    "HYPERLIQUID-BABY/USD-PERP": 189,
    "HYPERLIQUID-WCT/USD-PERP": 190,
    "HYPERLIQUID-HYPER/USD-PERP": 191,
    "HYPERLIQUID-ZORA/USD-PERP": 192,
    "HYPERLIQUID-INIT/USD-PERP": 193,
    "HYPERLIQUID-DOOD/USD-PERP": 194,
    "HYPERLIQUID-LAUNCHCOIN/USD-PERP": 195,
    "HYPERLIQUID-NXPC/USD-PERP": 196,
    "HYPERLIQUID-SOPH/USD-PERP": 197,
    "HYPERLIQUID-RESOLV/USD-PERP": 198,
}

# Reverse mapping (ID to symbol)
ID_TO_SYMBOL = {
    0: "HYPERLIQUID-BTC/USD-PERP",
    1: "HYPERLIQUID-ETH/USD-PERP",
    2: "HYPERLIQUID-ATOM/USD-PERP",
    4: "HYPERLIQUID-DYDX/USD-PERP",
    5: "HYPERLIQUID-SOL/USD-PERP",
    6: "HYPERLIQUID-AVAX/USD-PERP",
    7: "HYPERLIQUID-BNB/USD-PERP",
    8: "HYPERLIQUID-APE/USD-PERP",
    9: "HYPERLIQUID-OP/USD-PERP",
    10: "HYPERLIQUID-LTC/USD-PERP",
    11: "HYPERLIQUID-ARB/USD-PERP",
    12: "HYPERLIQUID-DOGE/USD-PERP",
    13: "HYPERLIQUID-INJ/USD-PERP",
    14: "HYPERLIQUID-SUI/USD-PERP",
    15: "HYPERLIQUID-kPEPE/USD-PERP",
    16: "HYPERLIQUID-CRV/USD-PERP",
    17: "HYPERLIQUID-LDO/USD-PERP",
    18: "HYPERLIQUID-LINK/USD-PERP",
    19: "HYPERLIQUID-STX/USD-PERP",
    21: "HYPERLIQUID-CFX/USD-PERP",
    23: "HYPERLIQUID-GMX/USD-PERP",
    24: "HYPERLIQUID-SNX/USD-PERP",
    25: "HYPERLIQUID-XRP/USD-PERP",
    26: "HYPERLIQUID-BCH/USD-PERP",
    27: "HYPERLIQUID-APT/USD-PERP",
    28: "HYPERLIQUID-AAVE/USD-PERP",
    29: "HYPERLIQUID-COMP/USD-PERP",
    30: "HYPERLIQUID-MKR/USD-PERP",
    31: "HYPERLIQUID-WLD/USD-PERP",
    32: "HYPERLIQUID-FXS/USD-PERP",
    36: "HYPERLIQUID-YGG/USD-PERP",
    37: "HYPERLIQUID-TRX/USD-PERP",
    38: "HYPERLIQUID-kSHIB/USD-PERP",
    39: "HYPERLIQUID-UNI/USD-PERP",
    40: "HYPERLIQUID-SEI/USD-PERP",
    41: "HYPERLIQUID-RUNE/USD-PERP",
    46: "HYPERLIQUID-ZRO/USD-PERP",
    48: "HYPERLIQUID-DOT/USD-PERP",
    49: "HYPERLIQUID-BANANA/USD-PERP",
    50: "HYPERLIQUID-TRB/USD-PERP",
    51: "HYPERLIQUID-FTT/USD-PERP",
    53: "HYPERLIQUID-OGN/USD-PERP",
    55: "HYPERLIQUID-ARK/USD-PERP",
    58: "HYPERLIQUID-REQ/USD-PERP",
    59: "HYPERLIQUID-BIGTIME/USD-PERP",
    60: "HYPERLIQUID-KAS/USD-PERP",
    62: "HYPERLIQUID-BLUR/USD-PERP",
    63: "HYPERLIQUID-TIA/USD-PERP",
    64: "HYPERLIQUID-BSV/USD-PERP",
    65: "HYPERLIQUID-ADA/USD-PERP",
    66: "HYPERLIQUID-TON/USD-PERP",
    67: "HYPERLIQUID-MINA/USD-PERP",
    68: "HYPERLIQUID-POLYX/USD-PERP",
    69: "HYPERLIQUID-GAS/USD-PERP",
    70: "HYPERLIQUID-PENDLE/USD-PERP",
    71: "HYPERLIQUID-STG/USD-PERP",
    72: "HYPERLIQUID-FET/USD-PERP",
    74: "HYPERLIQUID-NEAR/USD-PERP",
    75: "HYPERLIQUID-MEME/USD-PERP",
    76: "HYPERLIQUID-ORDI/USD-PERP",
    78: "HYPERLIQUID-NEO/USD-PERP",
    79: "HYPERLIQUID-ZEN/USD-PERP",
    80: "HYPERLIQUID-FIL/USD-PERP",
    81: "HYPERLIQUID-PYTH/USD-PERP",
    82: "HYPERLIQUID-SUSHI/USD-PERP",
    84: "HYPERLIQUID-IMX/USD-PERP",
    85: "HYPERLIQUID-kBONK/USD-PERP",
    86: "HYPERLIQUID-GMT/USD-PERP",
    87: "HYPERLIQUID-SUPER/USD-PERP",
    88: "HYPERLIQUID-USTC/USD-PERP",
    90: "HYPERLIQUID-JUP/USD-PERP",
    91: "HYPERLIQUID-kLUNC/USD-PERP",
    92: "HYPERLIQUID-RSR/USD-PERP",
    93: "HYPERLIQUID-GALA/USD-PERP",
    94: "HYPERLIQUID-JTO/USD-PERP",
    96: "HYPERLIQUID-ACE/USD-PERP",
    97: "HYPERLIQUID-MAV/USD-PERP",
    98: "HYPERLIQUID-WIF/USD-PERP",
    99: "HYPERLIQUID-CAKE/USD-PERP",
    100: "HYPERLIQUID-PEOPLE/USD-PERP",
    101: "HYPERLIQUID-ENS/USD-PERP",
    102: "HYPERLIQUID-ETC/USD-PERP",
    103: "HYPERLIQUID-XAI/USD-PERP",
    104: "HYPERLIQUID-MANTA/USD-PERP",
    105: "HYPERLIQUID-UMA/USD-PERP",
    106: "HYPERLIQUID-ONDO/USD-PERP",
    107: "HYPERLIQUID-ALT/USD-PERP",
    108: "HYPERLIQUID-ZETA/USD-PERP",
    109: "HYPERLIQUID-DYM/USD-PERP",
    110: "HYPERLIQUID-MAVIA/USD-PERP",
    111: "HYPERLIQUID-W/USD-PERP",
    113: "HYPERLIQUID-STRK/USD-PERP",
    116: "HYPERLIQUID-TAO/USD-PERP",
    117: "HYPERLIQUID-AR/USD-PERP",
    119: "HYPERLIQUID-kFLOKI/USD-PERP",
    120: "HYPERLIQUID-BOME/USD-PERP",
    121: "HYPERLIQUID-ETHFI/USD-PERP",
    122: "HYPERLIQUID-ENA/USD-PERP",
    123: "HYPERLIQUID-MNT/USD-PERP",
    124: "HYPERLIQUID-TNSR/USD-PERP",
    125: "HYPERLIQUID-SAGA/USD-PERP",
    126: "HYPERLIQUID-MERL/USD-PERP",
    127: "HYPERLIQUID-HBAR/USD-PERP",
    128: "HYPERLIQUID-POPCAT/USD-PERP",
    129: "HYPERLIQUID-OMNI/USD-PERP",
    130: "HYPERLIQUID-EIGEN/USD-PERP",
    131: "HYPERLIQUID-REZ/USD-PERP",
    132: "HYPERLIQUID-NOT/USD-PERP",
    133: "HYPERLIQUID-TURBO/USD-PERP",
    134: "HYPERLIQUID-BRETT/USD-PERP",
    135: "HYPERLIQUID-IO/USD-PERP",
    136: "HYPERLIQUID-ZK/USD-PERP",
    137: "HYPERLIQUID-BLAST/USD-PERP",
    139: "HYPERLIQUID-MEW/USD-PERP",
    140: "HYPERLIQUID-RENDER/USD-PERP",
    141: "HYPERLIQUID-kDOGS/USD-PERP",
    142: "HYPERLIQUID-POL/USD-PERP",
    144: "HYPERLIQUID-CELO/USD-PERP",
    145: "HYPERLIQUID-HMSTR/USD-PERP",
    146: "HYPERLIQUID-SCR/USD-PERP",
    147: "HYPERLIQUID-NEIROETH/USD-PERP",
    148: "HYPERLIQUID-kNEIRO/USD-PERP",
    149: "HYPERLIQUID-GOAT/USD-PERP",
    150: "HYPERLIQUID-MOODENG/USD-PERP",
    151: "HYPERLIQUID-GRASS/USD-PERP",
    152: "HYPERLIQUID-PURR/USD-PERP",
    153: "HYPERLIQUID-PNUT/USD-PERP",
    154: "HYPERLIQUID-XLM/USD-PERP",
    155: "HYPERLIQUID-CHILLGUY/USD-PERP",
    156: "HYPERLIQUID-SAND/USD-PERP",
    157: "HYPERLIQUID-IOTA/USD-PERP",
    158: "HYPERLIQUID-ALGO/USD-PERP",
    159: "HYPERLIQUID-HYPE/USD-PERP",
    160: "HYPERLIQUID-ME/USD-PERP",
    161: "HYPERLIQUID-MOVE/USD-PERP",
    162: "HYPERLIQUID-VIRTUAL/USD-PERP",
    163: "HYPERLIQUID-PENGU/USD-PERP",
    164: "HYPERLIQUID-USUAL/USD-PERP",
    165: "HYPERLIQUID-FARTCOIN/USD-PERP",
    166: "HYPERLIQUID-AI16Z/USD-PERP",
    167: "HYPERLIQUID-AIXBT/USD-PERP",
    168: "HYPERLIQUID-ZEREBRO/USD-PERP",
    169: "HYPERLIQUID-BIO/USD-PERP",
    170: "HYPERLIQUID-GRIFFAIN/USD-PERP",
    171: "HYPERLIQUID-SPX/USD-PERP",
    172: "HYPERLIQUID-S/USD-PERP",
    173: "HYPERLIQUID-MORPHO/USD-PERP",
    174: "HYPERLIQUID-TRUMP/USD-PERP",
    175: "HYPERLIQUID-MELANIA/USD-PERP",
    176: "HYPERLIQUID-ANIME/USD-PERP",
    177: "HYPERLIQUID-VINE/USD-PERP",
    178: "HYPERLIQUID-VVV/USD-PERP",
    180: "HYPERLIQUID-BERA/USD-PERP",
    181: "HYPERLIQUID-TST/USD-PERP",
    182: "HYPERLIQUID-LAYER/USD-PERP",
    183: "HYPERLIQUID-IP/USD-PERP",
    184: "HYPERLIQUID-OM/USD-PERP",
    185: "HYPERLIQUID-KAITO/USD-PERP",
    186: "HYPERLIQUID-NIL/USD-PERP",
    187: "HYPERLIQUID-PAXG/USD-PERP",
    188: "HYPERLIQUID-PROMPT/USD-PERP",
    189: "HYPERLIQUID-BABY/USD-PERP",
    190: "HYPERLIQUID-WCT/USD-PERP",
    191: "HYPERLIQUID-HYPER/USD-PERP",
    192: "HYPERLIQUID-ZORA/USD-PERP",
    193: "HYPERLIQUID-INIT/USD-PERP",
    194: "HYPERLIQUID-DOOD/USD-PERP",
    195: "HYPERLIQUID-LAUNCHCOIN/USD-PERP",
    196: "HYPERLIQUID-NXPC/USD-PERP",
    197: "HYPERLIQUID-SOPH/USD-PERP",
    198: "HYPERLIQUID-RESOLV/USD-PERP",
}

# Market metadata
MARKET_INFO = {
    0: {"symbol": "HYPERLIQUID-BTC/USD-PERP", "max_leverage": 40, "sz_decimals": 5},
    1: {"symbol": "HYPERLIQUID-ETH/USD-PERP", "max_leverage": 25, "sz_decimals": 4},
    2: {"symbol": "HYPERLIQUID-ATOM/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    4: {"symbol": "HYPERLIQUID-DYDX/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    5: {"symbol": "HYPERLIQUID-SOL/USD-PERP", "max_leverage": 20, "sz_decimals": 2},
    6: {"symbol": "HYPERLIQUID-AVAX/USD-PERP", "max_leverage": 10, "sz_decimals": 2},
    7: {"symbol": "HYPERLIQUID-BNB/USD-PERP", "max_leverage": 10, "sz_decimals": 3},
    8: {"symbol": "HYPERLIQUID-APE/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    9: {"symbol": "HYPERLIQUID-OP/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    10: {"symbol": "HYPERLIQUID-LTC/USD-PERP", "max_leverage": 10, "sz_decimals": 2},
    11: {"symbol": "HYPERLIQUID-ARB/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    12: {"symbol": "HYPERLIQUID-DOGE/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    13: {"symbol": "HYPERLIQUID-INJ/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    14: {"symbol": "HYPERLIQUID-SUI/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    15: {"symbol": "HYPERLIQUID-kPEPE/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    16: {"symbol": "HYPERLIQUID-CRV/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    17: {"symbol": "HYPERLIQUID-LDO/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    18: {"symbol": "HYPERLIQUID-LINK/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    19: {"symbol": "HYPERLIQUID-STX/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    21: {"symbol": "HYPERLIQUID-CFX/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    23: {"symbol": "HYPERLIQUID-GMX/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    24: {"symbol": "HYPERLIQUID-SNX/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    25: {"symbol": "HYPERLIQUID-XRP/USD-PERP", "max_leverage": 20, "sz_decimals": 0},
    26: {"symbol": "HYPERLIQUID-BCH/USD-PERP", "max_leverage": 10, "sz_decimals": 3},
    27: {"symbol": "HYPERLIQUID-APT/USD-PERP", "max_leverage": 10, "sz_decimals": 2},
    28: {"symbol": "HYPERLIQUID-AAVE/USD-PERP", "max_leverage": 10, "sz_decimals": 2},
    29: {"symbol": "HYPERLIQUID-COMP/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    30: {"symbol": "HYPERLIQUID-MKR/USD-PERP", "max_leverage": 10, "sz_decimals": 4},
    31: {"symbol": "HYPERLIQUID-WLD/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    32: {"symbol": "HYPERLIQUID-FXS/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    36: {"symbol": "HYPERLIQUID-YGG/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    37: {"symbol": "HYPERLIQUID-TRX/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    38: {"symbol": "HYPERLIQUID-kSHIB/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    39: {"symbol": "HYPERLIQUID-UNI/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    40: {"symbol": "HYPERLIQUID-SEI/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    41: {"symbol": "HYPERLIQUID-RUNE/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    46: {"symbol": "HYPERLIQUID-ZRO/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    48: {"symbol": "HYPERLIQUID-DOT/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    49: {"symbol": "HYPERLIQUID-BANANA/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    50: {"symbol": "HYPERLIQUID-TRB/USD-PERP", "max_leverage": 3, "sz_decimals": 2},
    51: {"symbol": "HYPERLIQUID-FTT/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    53: {"symbol": "HYPERLIQUID-OGN/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    55: {"symbol": "HYPERLIQUID-ARK/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    58: {"symbol": "HYPERLIQUID-REQ/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    59: {"symbol": "HYPERLIQUID-BIGTIME/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    60: {"symbol": "HYPERLIQUID-KAS/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    62: {"symbol": "HYPERLIQUID-BLUR/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    63: {"symbol": "HYPERLIQUID-TIA/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    64: {"symbol": "HYPERLIQUID-BSV/USD-PERP", "max_leverage": 3, "sz_decimals": 2},
    65: {"symbol": "HYPERLIQUID-ADA/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    66: {"symbol": "HYPERLIQUID-TON/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    67: {"symbol": "HYPERLIQUID-MINA/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    68: {"symbol": "HYPERLIQUID-POLYX/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    69: {"symbol": "HYPERLIQUID-GAS/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    70: {"symbol": "HYPERLIQUID-PENDLE/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    71: {"symbol": "HYPERLIQUID-STG/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    72: {"symbol": "HYPERLIQUID-FET/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    74: {"symbol": "HYPERLIQUID-NEAR/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    75: {"symbol": "HYPERLIQUID-MEME/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    76: {"symbol": "HYPERLIQUID-ORDI/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    78: {"symbol": "HYPERLIQUID-NEO/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    79: {"symbol": "HYPERLIQUID-ZEN/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    80: {"symbol": "HYPERLIQUID-FIL/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    81: {"symbol": "HYPERLIQUID-PYTH/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    82: {"symbol": "HYPERLIQUID-SUSHI/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    84: {"symbol": "HYPERLIQUID-IMX/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    85: {"symbol": "HYPERLIQUID-kBONK/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    86: {"symbol": "HYPERLIQUID-GMT/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    87: {"symbol": "HYPERLIQUID-SUPER/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    88: {"symbol": "HYPERLIQUID-USTC/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    90: {"symbol": "HYPERLIQUID-JUP/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    91: {"symbol": "HYPERLIQUID-kLUNC/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    92: {"symbol": "HYPERLIQUID-RSR/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    93: {"symbol": "HYPERLIQUID-GALA/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    94: {"symbol": "HYPERLIQUID-JTO/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    96: {"symbol": "HYPERLIQUID-ACE/USD-PERP", "max_leverage": 3, "sz_decimals": 2},
    97: {"symbol": "HYPERLIQUID-MAV/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    98: {"symbol": "HYPERLIQUID-WIF/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    99: {"symbol": "HYPERLIQUID-CAKE/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    100: {"symbol": "HYPERLIQUID-PEOPLE/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    101: {"symbol": "HYPERLIQUID-ENS/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    102: {"symbol": "HYPERLIQUID-ETC/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    103: {"symbol": "HYPERLIQUID-XAI/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    104: {"symbol": "HYPERLIQUID-MANTA/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    105: {"symbol": "HYPERLIQUID-UMA/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    106: {"symbol": "HYPERLIQUID-ONDO/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    107: {"symbol": "HYPERLIQUID-ALT/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    108: {"symbol": "HYPERLIQUID-ZETA/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    109: {"symbol": "HYPERLIQUID-DYM/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    110: {"symbol": "HYPERLIQUID-MAVIA/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    111: {"symbol": "HYPERLIQUID-W/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    113: {"symbol": "HYPERLIQUID-STRK/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    116: {"symbol": "HYPERLIQUID-TAO/USD-PERP", "max_leverage": 5, "sz_decimals": 3},
    117: {"symbol": "HYPERLIQUID-AR/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    119: {"symbol": "HYPERLIQUID-kFLOKI/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    120: {"symbol": "HYPERLIQUID-BOME/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    121: {"symbol": "HYPERLIQUID-ETHFI/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    122: {"symbol": "HYPERLIQUID-ENA/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    123: {"symbol": "HYPERLIQUID-MNT/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    124: {"symbol": "HYPERLIQUID-TNSR/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    125: {"symbol": "HYPERLIQUID-SAGA/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    126: {"symbol": "HYPERLIQUID-MERL/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    127: {"symbol": "HYPERLIQUID-HBAR/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    128: {"symbol": "HYPERLIQUID-POPCAT/USD-PERP", "max_leverage": 10, "sz_decimals": 0},
    129: {"symbol": "HYPERLIQUID-OMNI/USD-PERP", "max_leverage": 3, "sz_decimals": 2},
    130: {"symbol": "HYPERLIQUID-EIGEN/USD-PERP", "max_leverage": 5, "sz_decimals": 2},
    131: {"symbol": "HYPERLIQUID-REZ/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    132: {"symbol": "HYPERLIQUID-NOT/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    133: {"symbol": "HYPERLIQUID-TURBO/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    134: {"symbol": "HYPERLIQUID-BRETT/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    135: {"symbol": "HYPERLIQUID-IO/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    136: {"symbol": "HYPERLIQUID-ZK/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    137: {"symbol": "HYPERLIQUID-BLAST/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    139: {"symbol": "HYPERLIQUID-MEW/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    140: {"symbol": "HYPERLIQUID-RENDER/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    141: {"symbol": "HYPERLIQUID-kDOGS/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    142: {"symbol": "HYPERLIQUID-POL/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    144: {"symbol": "HYPERLIQUID-CELO/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    145: {"symbol": "HYPERLIQUID-HMSTR/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    146: {"symbol": "HYPERLIQUID-SCR/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    147: {"symbol": "HYPERLIQUID-NEIROETH/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    148: {"symbol": "HYPERLIQUID-kNEIRO/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    149: {"symbol": "HYPERLIQUID-GOAT/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    150: {"symbol": "HYPERLIQUID-MOODENG/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    151: {"symbol": "HYPERLIQUID-GRASS/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    152: {"symbol": "HYPERLIQUID-PURR/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    153: {"symbol": "HYPERLIQUID-PNUT/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    154: {"symbol": "HYPERLIQUID-XLM/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    155: {"symbol": "HYPERLIQUID-CHILLGUY/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    156: {"symbol": "HYPERLIQUID-SAND/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    157: {"symbol": "HYPERLIQUID-IOTA/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    158: {"symbol": "HYPERLIQUID-ALGO/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    159: {"symbol": "HYPERLIQUID-HYPE/USD-PERP", "max_leverage": 10, "sz_decimals": 2},
    160: {"symbol": "HYPERLIQUID-ME/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    161: {"symbol": "HYPERLIQUID-MOVE/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    162: {"symbol": "HYPERLIQUID-VIRTUAL/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    163: {"symbol": "HYPERLIQUID-PENGU/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    164: {"symbol": "HYPERLIQUID-USUAL/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    165: {"symbol": "HYPERLIQUID-FARTCOIN/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    166: {"symbol": "HYPERLIQUID-AI16Z/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    167: {"symbol": "HYPERLIQUID-AIXBT/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    168: {"symbol": "HYPERLIQUID-ZEREBRO/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    169: {"symbol": "HYPERLIQUID-BIO/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    170: {"symbol": "HYPERLIQUID-GRIFFAIN/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    171: {"symbol": "HYPERLIQUID-SPX/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    172: {"symbol": "HYPERLIQUID-S/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    173: {"symbol": "HYPERLIQUID-MORPHO/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    174: {"symbol": "HYPERLIQUID-TRUMP/USD-PERP", "max_leverage": 10, "sz_decimals": 1},
    175: {"symbol": "HYPERLIQUID-MELANIA/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    176: {"symbol": "HYPERLIQUID-ANIME/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    177: {"symbol": "HYPERLIQUID-VINE/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    178: {"symbol": "HYPERLIQUID-VVV/USD-PERP", "max_leverage": 3, "sz_decimals": 2},
    180: {"symbol": "HYPERLIQUID-BERA/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    181: {"symbol": "HYPERLIQUID-TST/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    182: {"symbol": "HYPERLIQUID-LAYER/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    183: {"symbol": "HYPERLIQUID-IP/USD-PERP", "max_leverage": 3, "sz_decimals": 1},
    184: {"symbol": "HYPERLIQUID-OM/USD-PERP", "max_leverage": 5, "sz_decimals": 1},
    185: {"symbol": "HYPERLIQUID-KAITO/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    186: {"symbol": "HYPERLIQUID-NIL/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    187: {"symbol": "HYPERLIQUID-PAXG/USD-PERP", "max_leverage": 5, "sz_decimals": 3},
    188: {"symbol": "HYPERLIQUID-PROMPT/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    189: {"symbol": "HYPERLIQUID-BABY/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    190: {"symbol": "HYPERLIQUID-WCT/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    191: {"symbol": "HYPERLIQUID-HYPER/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    192: {"symbol": "HYPERLIQUID-ZORA/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    193: {"symbol": "HYPERLIQUID-INIT/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    194: {"symbol": "HYPERLIQUID-DOOD/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    195: {"symbol": "HYPERLIQUID-LAUNCHCOIN/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
    196: {"symbol": "HYPERLIQUID-NXPC/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    197: {"symbol": "HYPERLIQUID-SOPH/USD-PERP", "max_leverage": 5, "sz_decimals": 0},
    198: {"symbol": "HYPERLIQUID-RESOLV/USD-PERP", "max_leverage": 3, "sz_decimals": 0},
}

# Get market ID by symbol
def get_market_id(symbol):
    """Get market ID from symbol. Supports both old (BTC) and new (HYPERLIQUID-BTC/USD-PERP) formats."""
    # Try direct lookup first
    if symbol in MARKET_IDS:
        return MARKET_IDS[symbol]
    
    # Try converting old format to new format
    new_symbol = f"HYPERLIQUID-{symbol}/USD-PERP"
    return MARKET_IDS.get(new_symbol)

# Get symbol by market ID
def get_symbol(market_id):
    """Get symbol from market ID"""
    return ID_TO_SYMBOL.get(market_id)

# Get all active market IDs
def get_all_market_ids():
    """Get list of all active market IDs"""
    return sorted(ID_TO_SYMBOL.keys())

# Get all active symbols
def get_all_symbols():
    """Get list of all active symbols"""
    return sorted(MARKET_IDS.keys())
