#!/usr/bin/env python3
"""
Hyperliquid market configuration for Python clients.
Auto-generated on: 2025-06-24 20:42:03
Total active markets: 171
"""

# Market symbol to ID mapping
MARKET_IDS = {
    "BTC": 0,
    "ETH": 1,
    "ATOM": 2,
    "DYDX": 4,
    "SOL": 5,
    "AVAX": 6,
    "BNB": 7,
    "APE": 8,
    "OP": 9,
    "LTC": 10,
    "ARB": 11,
    "DOGE": 12,
    "INJ": 13,
    "SUI": 14,
    "kPEPE": 15,
    "CRV": 16,
    "LDO": 17,
    "LINK": 18,
    "STX": 19,
    "CFX": 21,
    "GMX": 23,
    "SNX": 24,
    "XRP": 25,
    "BCH": 26,
    "APT": 27,
    "AAVE": 28,
    "COMP": 29,
    "MKR": 30,
    "WLD": 31,
    "FXS": 32,
    "YGG": 36,
    "TRX": 37,
    "kSHIB": 38,
    "UNI": 39,
    "SEI": 40,
    "RUNE": 41,
    "ZRO": 46,
    "DOT": 48,
    "BANANA": 49,
    "TRB": 50,
    "FTT": 51,
    "OGN": 53,
    "ARK": 55,
    "REQ": 58,
    "BIGTIME": 59,
    "KAS": 60,
    "BLUR": 62,
    "TIA": 63,
    "BSV": 64,
    "ADA": 65,
    "TON": 66,
    "MINA": 67,
    "POLYX": 68,
    "GAS": 69,
    "PENDLE": 70,
    "STG": 71,
    "FET": 72,
    "NEAR": 74,
    "MEME": 75,
    "ORDI": 76,
    "NEO": 78,
    "ZEN": 79,
    "FIL": 80,
    "PYTH": 81,
    "SUSHI": 82,
    "IMX": 84,
    "kBONK": 85,
    "GMT": 86,
    "SUPER": 87,
    "USTC": 88,
    "JUP": 90,
    "kLUNC": 91,
    "RSR": 92,
    "GALA": 93,
    "JTO": 94,
    "ACE": 96,
    "MAV": 97,
    "WIF": 98,
    "CAKE": 99,
    "PEOPLE": 100,
    "ENS": 101,
    "ETC": 102,
    "XAI": 103,
    "MANTA": 104,
    "UMA": 105,
    "ONDO": 106,
    "ALT": 107,
    "ZETA": 108,
    "DYM": 109,
    "MAVIA": 110,
    "W": 111,
    "STRK": 113,
    "TAO": 116,
    "AR": 117,
    "kFLOKI": 119,
    "BOME": 120,
    "ETHFI": 121,
    "ENA": 122,
    "MNT": 123,
    "TNSR": 124,
    "SAGA": 125,
    "MERL": 126,
    "HBAR": 127,
    "POPCAT": 128,
    "OMNI": 129,
    "EIGEN": 130,
    "REZ": 131,
    "NOT": 132,
    "TURBO": 133,
    "BRETT": 134,
    "IO": 135,
    "ZK": 136,
    "BLAST": 137,
    "MEW": 139,
    "RENDER": 140,
    "kDOGS": 141,
    "POL": 142,
    "CELO": 144,
    "HMSTR": 145,
    "SCR": 146,
    "NEIROETH": 147,
    "kNEIRO": 148,
    "GOAT": 149,
    "MOODENG": 150,
    "GRASS": 151,
    "PURR": 152,
    "PNUT": 153,
    "XLM": 154,
    "CHILLGUY": 155,
    "SAND": 156,
    "IOTA": 157,
    "ALGO": 158,
    "HYPE": 159,
    "ME": 160,
    "MOVE": 161,
    "VIRTUAL": 162,
    "PENGU": 163,
    "USUAL": 164,
    "FARTCOIN": 165,
    "AI16Z": 166,
    "AIXBT": 167,
    "ZEREBRO": 168,
    "BIO": 169,
    "GRIFFAIN": 170,
    "SPX": 171,
    "S": 172,
    "MORPHO": 173,
    "TRUMP": 174,
    "MELANIA": 175,
    "ANIME": 176,
    "VINE": 177,
    "VVV": 178,
    "BERA": 180,
    "TST": 181,
    "LAYER": 182,
    "IP": 183,
    "OM": 184,
    "KAITO": 185,
    "NIL": 186,
    "PAXG": 187,
    "PROMPT": 188,
    "BABY": 189,
    "WCT": 190,
    "HYPER": 191,
    "ZORA": 192,
    "INIT": 193,
    "DOOD": 194,
    "LAUNCHCOIN": 195,
    "NXPC": 196,
    "SOPH": 197,
    "RESOLV": 198,
}

# Reverse mapping (ID to symbol)
ID_TO_SYMBOL = {
    0: "BTC",
    1: "ETH",
    2: "ATOM",
    4: "DYDX",
    5: "SOL",
    6: "AVAX",
    7: "BNB",
    8: "APE",
    9: "OP",
    10: "LTC",
    11: "ARB",
    12: "DOGE",
    13: "INJ",
    14: "SUI",
    15: "kPEPE",
    16: "CRV",
    17: "LDO",
    18: "LINK",
    19: "STX",
    21: "CFX",
    23: "GMX",
    24: "SNX",
    25: "XRP",
    26: "BCH",
    27: "APT",
    28: "AAVE",
    29: "COMP",
    30: "MKR",
    31: "WLD",
    32: "FXS",
    36: "YGG",
    37: "TRX",
    38: "kSHIB",
    39: "UNI",
    40: "SEI",
    41: "RUNE",
    46: "ZRO",
    48: "DOT",
    49: "BANANA",
    50: "TRB",
    51: "FTT",
    53: "OGN",
    55: "ARK",
    58: "REQ",
    59: "BIGTIME",
    60: "KAS",
    62: "BLUR",
    63: "TIA",
    64: "BSV",
    65: "ADA",
    66: "TON",
    67: "MINA",
    68: "POLYX",
    69: "GAS",
    70: "PENDLE",
    71: "STG",
    72: "FET",
    74: "NEAR",
    75: "MEME",
    76: "ORDI",
    78: "NEO",
    79: "ZEN",
    80: "FIL",
    81: "PYTH",
    82: "SUSHI",
    84: "IMX",
    85: "kBONK",
    86: "GMT",
    87: "SUPER",
    88: "USTC",
    90: "JUP",
    91: "kLUNC",
    92: "RSR",
    93: "GALA",
    94: "JTO",
    96: "ACE",
    97: "MAV",
    98: "WIF",
    99: "CAKE",
    100: "PEOPLE",
    101: "ENS",
    102: "ETC",
    103: "XAI",
    104: "MANTA",
    105: "UMA",
    106: "ONDO",
    107: "ALT",
    108: "ZETA",
    109: "DYM",
    110: "MAVIA",
    111: "W",
    113: "STRK",
    116: "TAO",
    117: "AR",
    119: "kFLOKI",
    120: "BOME",
    121: "ETHFI",
    122: "ENA",
    123: "MNT",
    124: "TNSR",
    125: "SAGA",
    126: "MERL",
    127: "HBAR",
    128: "POPCAT",
    129: "OMNI",
    130: "EIGEN",
    131: "REZ",
    132: "NOT",
    133: "TURBO",
    134: "BRETT",
    135: "IO",
    136: "ZK",
    137: "BLAST",
    139: "MEW",
    140: "RENDER",
    141: "kDOGS",
    142: "POL",
    144: "CELO",
    145: "HMSTR",
    146: "SCR",
    147: "NEIROETH",
    148: "kNEIRO",
    149: "GOAT",
    150: "MOODENG",
    151: "GRASS",
    152: "PURR",
    153: "PNUT",
    154: "XLM",
    155: "CHILLGUY",
    156: "SAND",
    157: "IOTA",
    158: "ALGO",
    159: "HYPE",
    160: "ME",
    161: "MOVE",
    162: "VIRTUAL",
    163: "PENGU",
    164: "USUAL",
    165: "FARTCOIN",
    166: "AI16Z",
    167: "AIXBT",
    168: "ZEREBRO",
    169: "BIO",
    170: "GRIFFAIN",
    171: "SPX",
    172: "S",
    173: "MORPHO",
    174: "TRUMP",
    175: "MELANIA",
    176: "ANIME",
    177: "VINE",
    178: "VVV",
    180: "BERA",
    181: "TST",
    182: "LAYER",
    183: "IP",
    184: "OM",
    185: "KAITO",
    186: "NIL",
    187: "PAXG",
    188: "PROMPT",
    189: "BABY",
    190: "WCT",
    191: "HYPER",
    192: "ZORA",
    193: "INIT",
    194: "DOOD",
    195: "LAUNCHCOIN",
    196: "NXPC",
    197: "SOPH",
    198: "RESOLV",
}

# Market metadata
MARKET_INFO = {
    0: {"symbol": "BTC", "max_leverage": 40, "sz_decimals": 5},
    1: {"symbol": "ETH", "max_leverage": 25, "sz_decimals": 4},
    2: {"symbol": "ATOM", "max_leverage": 5, "sz_decimals": 2},
    4: {"symbol": "DYDX", "max_leverage": 5, "sz_decimals": 1},
    5: {"symbol": "SOL", "max_leverage": 20, "sz_decimals": 2},
    6: {"symbol": "AVAX", "max_leverage": 10, "sz_decimals": 2},
    7: {"symbol": "BNB", "max_leverage": 10, "sz_decimals": 3},
    8: {"symbol": "APE", "max_leverage": 5, "sz_decimals": 1},
    9: {"symbol": "OP", "max_leverage": 10, "sz_decimals": 1},
    10: {"symbol": "LTC", "max_leverage": 10, "sz_decimals": 2},
    11: {"symbol": "ARB", "max_leverage": 10, "sz_decimals": 1},
    12: {"symbol": "DOGE", "max_leverage": 10, "sz_decimals": 0},
    13: {"symbol": "INJ", "max_leverage": 10, "sz_decimals": 1},
    14: {"symbol": "SUI", "max_leverage": 10, "sz_decimals": 1},
    15: {"symbol": "kPEPE", "max_leverage": 10, "sz_decimals": 0},
    16: {"symbol": "CRV", "max_leverage": 10, "sz_decimals": 1},
    17: {"symbol": "LDO", "max_leverage": 10, "sz_decimals": 1},
    18: {"symbol": "LINK", "max_leverage": 10, "sz_decimals": 1},
    19: {"symbol": "STX", "max_leverage": 5, "sz_decimals": 1},
    21: {"symbol": "CFX", "max_leverage": 5, "sz_decimals": 0},
    23: {"symbol": "GMX", "max_leverage": 5, "sz_decimals": 2},
    24: {"symbol": "SNX", "max_leverage": 3, "sz_decimals": 1},
    25: {"symbol": "XRP", "max_leverage": 20, "sz_decimals": 0},
    26: {"symbol": "BCH", "max_leverage": 10, "sz_decimals": 3},
    27: {"symbol": "APT", "max_leverage": 10, "sz_decimals": 2},
    28: {"symbol": "AAVE", "max_leverage": 10, "sz_decimals": 2},
    29: {"symbol": "COMP", "max_leverage": 5, "sz_decimals": 2},
    30: {"symbol": "MKR", "max_leverage": 10, "sz_decimals": 4},
    31: {"symbol": "WLD", "max_leverage": 10, "sz_decimals": 1},
    32: {"symbol": "FXS", "max_leverage": 5, "sz_decimals": 1},
    36: {"symbol": "YGG", "max_leverage": 3, "sz_decimals": 0},
    37: {"symbol": "TRX", "max_leverage": 10, "sz_decimals": 0},
    38: {"symbol": "kSHIB", "max_leverage": 10, "sz_decimals": 0},
    39: {"symbol": "UNI", "max_leverage": 10, "sz_decimals": 1},
    40: {"symbol": "SEI", "max_leverage": 10, "sz_decimals": 0},
    41: {"symbol": "RUNE", "max_leverage": 5, "sz_decimals": 1},
    46: {"symbol": "ZRO", "max_leverage": 5, "sz_decimals": 1},
    48: {"symbol": "DOT", "max_leverage": 10, "sz_decimals": 1},
    49: {"symbol": "BANANA", "max_leverage": 3, "sz_decimals": 1},
    50: {"symbol": "TRB", "max_leverage": 3, "sz_decimals": 2},
    51: {"symbol": "FTT", "max_leverage": 3, "sz_decimals": 1},
    53: {"symbol": "OGN", "max_leverage": 3, "sz_decimals": 0},
    55: {"symbol": "ARK", "max_leverage": 3, "sz_decimals": 0},
    58: {"symbol": "REQ", "max_leverage": 3, "sz_decimals": 0},
    59: {"symbol": "BIGTIME", "max_leverage": 5, "sz_decimals": 0},
    60: {"symbol": "KAS", "max_leverage": 3, "sz_decimals": 0},
    62: {"symbol": "BLUR", "max_leverage": 5, "sz_decimals": 0},
    63: {"symbol": "TIA", "max_leverage": 10, "sz_decimals": 1},
    64: {"symbol": "BSV", "max_leverage": 3, "sz_decimals": 2},
    65: {"symbol": "ADA", "max_leverage": 10, "sz_decimals": 0},
    66: {"symbol": "TON", "max_leverage": 10, "sz_decimals": 1},
    67: {"symbol": "MINA", "max_leverage": 3, "sz_decimals": 0},
    68: {"symbol": "POLYX", "max_leverage": 3, "sz_decimals": 0},
    69: {"symbol": "GAS", "max_leverage": 3, "sz_decimals": 1},
    70: {"symbol": "PENDLE", "max_leverage": 5, "sz_decimals": 0},
    71: {"symbol": "STG", "max_leverage": 3, "sz_decimals": 0},
    72: {"symbol": "FET", "max_leverage": 5, "sz_decimals": 0},
    74: {"symbol": "NEAR", "max_leverage": 10, "sz_decimals": 1},
    75: {"symbol": "MEME", "max_leverage": 5, "sz_decimals": 0},
    76: {"symbol": "ORDI", "max_leverage": 5, "sz_decimals": 2},
    78: {"symbol": "NEO", "max_leverage": 5, "sz_decimals": 2},
    79: {"symbol": "ZEN", "max_leverage": 5, "sz_decimals": 2},
    80: {"symbol": "FIL", "max_leverage": 5, "sz_decimals": 1},
    81: {"symbol": "PYTH", "max_leverage": 5, "sz_decimals": 0},
    82: {"symbol": "SUSHI", "max_leverage": 5, "sz_decimals": 1},
    84: {"symbol": "IMX", "max_leverage": 5, "sz_decimals": 1},
    85: {"symbol": "kBONK", "max_leverage": 10, "sz_decimals": 0},
    86: {"symbol": "GMT", "max_leverage": 5, "sz_decimals": 0},
    87: {"symbol": "SUPER", "max_leverage": 3, "sz_decimals": 0},
    88: {"symbol": "USTC", "max_leverage": 3, "sz_decimals": 0},
    90: {"symbol": "JUP", "max_leverage": 10, "sz_decimals": 0},
    91: {"symbol": "kLUNC", "max_leverage": 3, "sz_decimals": 0},
    92: {"symbol": "RSR", "max_leverage": 3, "sz_decimals": 0},
    93: {"symbol": "GALA", "max_leverage": 3, "sz_decimals": 0},
    94: {"symbol": "JTO", "max_leverage": 5, "sz_decimals": 0},
    96: {"symbol": "ACE", "max_leverage": 3, "sz_decimals": 2},
    97: {"symbol": "MAV", "max_leverage": 3, "sz_decimals": 0},
    98: {"symbol": "WIF", "max_leverage": 10, "sz_decimals": 0},
    99: {"symbol": "CAKE", "max_leverage": 3, "sz_decimals": 1},
    100: {"symbol": "PEOPLE", "max_leverage": 3, "sz_decimals": 0},
    101: {"symbol": "ENS", "max_leverage": 5, "sz_decimals": 2},
    102: {"symbol": "ETC", "max_leverage": 5, "sz_decimals": 2},
    103: {"symbol": "XAI", "max_leverage": 3, "sz_decimals": 1},
    104: {"symbol": "MANTA", "max_leverage": 3, "sz_decimals": 1},
    105: {"symbol": "UMA", "max_leverage": 3, "sz_decimals": 1},
    106: {"symbol": "ONDO", "max_leverage": 10, "sz_decimals": 0},
    107: {"symbol": "ALT", "max_leverage": 5, "sz_decimals": 0},
    108: {"symbol": "ZETA", "max_leverage": 3, "sz_decimals": 1},
    109: {"symbol": "DYM", "max_leverage": 3, "sz_decimals": 1},
    110: {"symbol": "MAVIA", "max_leverage": 3, "sz_decimals": 1},
    111: {"symbol": "W", "max_leverage": 5, "sz_decimals": 1},
    113: {"symbol": "STRK", "max_leverage": 5, "sz_decimals": 1},
    116: {"symbol": "TAO", "max_leverage": 5, "sz_decimals": 3},
    117: {"symbol": "AR", "max_leverage": 5, "sz_decimals": 2},
    119: {"symbol": "kFLOKI", "max_leverage": 5, "sz_decimals": 0},
    120: {"symbol": "BOME", "max_leverage": 3, "sz_decimals": 0},
    121: {"symbol": "ETHFI", "max_leverage": 5, "sz_decimals": 1},
    122: {"symbol": "ENA", "max_leverage": 10, "sz_decimals": 0},
    123: {"symbol": "MNT", "max_leverage": 5, "sz_decimals": 1},
    124: {"symbol": "TNSR", "max_leverage": 3, "sz_decimals": 1},
    125: {"symbol": "SAGA", "max_leverage": 5, "sz_decimals": 1},
    126: {"symbol": "MERL", "max_leverage": 3, "sz_decimals": 0},
    127: {"symbol": "HBAR", "max_leverage": 5, "sz_decimals": 0},
    128: {"symbol": "POPCAT", "max_leverage": 10, "sz_decimals": 0},
    129: {"symbol": "OMNI", "max_leverage": 3, "sz_decimals": 2},
    130: {"symbol": "EIGEN", "max_leverage": 5, "sz_decimals": 2},
    131: {"symbol": "REZ", "max_leverage": 3, "sz_decimals": 0},
    132: {"symbol": "NOT", "max_leverage": 3, "sz_decimals": 0},
    133: {"symbol": "TURBO", "max_leverage": 5, "sz_decimals": 0},
    134: {"symbol": "BRETT", "max_leverage": 5, "sz_decimals": 0},
    135: {"symbol": "IO", "max_leverage": 5, "sz_decimals": 1},
    136: {"symbol": "ZK", "max_leverage": 5, "sz_decimals": 0},
    137: {"symbol": "BLAST", "max_leverage": 3, "sz_decimals": 0},
    139: {"symbol": "MEW", "max_leverage": 5, "sz_decimals": 0},
    140: {"symbol": "RENDER", "max_leverage": 5, "sz_decimals": 1},
    141: {"symbol": "kDOGS", "max_leverage": 3, "sz_decimals": 0},
    142: {"symbol": "POL", "max_leverage": 5, "sz_decimals": 0},
    144: {"symbol": "CELO", "max_leverage": 3, "sz_decimals": 0},
    145: {"symbol": "HMSTR", "max_leverage": 3, "sz_decimals": 0},
    146: {"symbol": "SCR", "max_leverage": 5, "sz_decimals": 1},
    147: {"symbol": "NEIROETH", "max_leverage": 5, "sz_decimals": 0},
    148: {"symbol": "kNEIRO", "max_leverage": 5, "sz_decimals": 1},
    149: {"symbol": "GOAT", "max_leverage": 5, "sz_decimals": 0},
    150: {"symbol": "MOODENG", "max_leverage": 5, "sz_decimals": 0},
    151: {"symbol": "GRASS", "max_leverage": 5, "sz_decimals": 1},
    152: {"symbol": "PURR", "max_leverage": 3, "sz_decimals": 0},
    153: {"symbol": "PNUT", "max_leverage": 5, "sz_decimals": 1},
    154: {"symbol": "XLM", "max_leverage": 5, "sz_decimals": 0},
    155: {"symbol": "CHILLGUY", "max_leverage": 3, "sz_decimals": 0},
    156: {"symbol": "SAND", "max_leverage": 5, "sz_decimals": 0},
    157: {"symbol": "IOTA", "max_leverage": 3, "sz_decimals": 0},
    158: {"symbol": "ALGO", "max_leverage": 5, "sz_decimals": 0},
    159: {"symbol": "HYPE", "max_leverage": 10, "sz_decimals": 2},
    160: {"symbol": "ME", "max_leverage": 5, "sz_decimals": 1},
    161: {"symbol": "MOVE", "max_leverage": 5, "sz_decimals": 0},
    162: {"symbol": "VIRTUAL", "max_leverage": 5, "sz_decimals": 1},
    163: {"symbol": "PENGU", "max_leverage": 5, "sz_decimals": 0},
    164: {"symbol": "USUAL", "max_leverage": 5, "sz_decimals": 1},
    165: {"symbol": "FARTCOIN", "max_leverage": 10, "sz_decimals": 1},
    166: {"symbol": "AI16Z", "max_leverage": 5, "sz_decimals": 1},
    167: {"symbol": "AIXBT", "max_leverage": 5, "sz_decimals": 0},
    168: {"symbol": "ZEREBRO", "max_leverage": 5, "sz_decimals": 0},
    169: {"symbol": "BIO", "max_leverage": 5, "sz_decimals": 0},
    170: {"symbol": "GRIFFAIN", "max_leverage": 5, "sz_decimals": 0},
    171: {"symbol": "SPX", "max_leverage": 5, "sz_decimals": 1},
    172: {"symbol": "S", "max_leverage": 5, "sz_decimals": 0},
    173: {"symbol": "MORPHO", "max_leverage": 5, "sz_decimals": 1},
    174: {"symbol": "TRUMP", "max_leverage": 10, "sz_decimals": 1},
    175: {"symbol": "MELANIA", "max_leverage": 5, "sz_decimals": 1},
    176: {"symbol": "ANIME", "max_leverage": 3, "sz_decimals": 0},
    177: {"symbol": "VINE", "max_leverage": 5, "sz_decimals": 0},
    178: {"symbol": "VVV", "max_leverage": 3, "sz_decimals": 2},
    180: {"symbol": "BERA", "max_leverage": 5, "sz_decimals": 1},
    181: {"symbol": "TST", "max_leverage": 3, "sz_decimals": 0},
    182: {"symbol": "LAYER", "max_leverage": 3, "sz_decimals": 0},
    183: {"symbol": "IP", "max_leverage": 3, "sz_decimals": 1},
    184: {"symbol": "OM", "max_leverage": 5, "sz_decimals": 1},
    185: {"symbol": "KAITO", "max_leverage": 5, "sz_decimals": 0},
    186: {"symbol": "NIL", "max_leverage": 3, "sz_decimals": 0},
    187: {"symbol": "PAXG", "max_leverage": 5, "sz_decimals": 3},
    188: {"symbol": "PROMPT", "max_leverage": 5, "sz_decimals": 0},
    189: {"symbol": "BABY", "max_leverage": 5, "sz_decimals": 0},
    190: {"symbol": "WCT", "max_leverage": 3, "sz_decimals": 0},
    191: {"symbol": "HYPER", "max_leverage": 3, "sz_decimals": 0},
    192: {"symbol": "ZORA", "max_leverage": 3, "sz_decimals": 0},
    193: {"symbol": "INIT", "max_leverage": 3, "sz_decimals": 0},
    194: {"symbol": "DOOD", "max_leverage": 3, "sz_decimals": 0},
    195: {"symbol": "LAUNCHCOIN", "max_leverage": 3, "sz_decimals": 0},
    196: {"symbol": "NXPC", "max_leverage": 5, "sz_decimals": 0},
    197: {"symbol": "SOPH", "max_leverage": 5, "sz_decimals": 0},
    198: {"symbol": "RESOLV", "max_leverage": 3, "sz_decimals": 0},
}

# Get market ID by symbol
def get_market_id(symbol):
    """Get market ID from symbol"""
    return MARKET_IDS.get(symbol)

# Get symbol by market ID
def get_symbol(market_id):
    """Get symbol from market ID"""
    return ID_TO_SYMBOL.get(market_id)

# Get all active market IDs
def get_all_market_ids():
    """Get list of all active market IDs"""
    return sorted(ID_TO_SYMBOL.keys())

# Get all active symbols
def get_all_symbols():
    """Get list of all active symbols"""
    return sorted(MARKET_IDS.keys())
