# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbook.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'orderbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderbook.proto\x12\torderbook\"Q\n\x10SubscribeRequest\x12\x12\n\nmarket_ids\x18\x01 \x03(\r\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\x12\x1a\n\x12update_interval_ms\x18\x03 \x01(\x04\"7\n\x13GetOrderbookRequest\x12\x11\n\tmarket_id\x18\x01 \x01(\r\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\"\x13\n\x11GetMarketsRequest\"<\n\x12GetMarketsResponse\x12&\n\x07markets\x18\x01 \x03(\x0b\x32\x15.orderbook.MarketInfo\"?\n\nMarketInfo\x12\x11\n\tmarket_id\x18\x01 \x01(\r\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\"\xa8\x01\n\x11OrderbookSnapshot\x12\x11\n\tmarket_id\x18\x01 \x01(\r\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x04\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x04\x12#\n\x04\x62ids\x18\x05 \x03(\x0b\x32\x15.orderbook.PriceLevel\x12#\n\x04\x61sks\x18\x06 \x03(\x0b\x32\x15.orderbook.PriceLevel\"B\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\x13\n\x0border_count\x18\x03 \x01(\r\"\\\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x04\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0c\n\x04size\x18\x03 \x01(\x01\x12\x0e\n\x06is_buy\x18\x04 \x01(\x08\x12\x14\n\x0ctimestamp_us\x18\x05 \x01(\x04\x32\xfe\x01\n\x10OrderbookService\x12Q\n\x12SubscribeOrderbook\x12\x1b.orderbook.SubscribeRequest\x1a\x1c.orderbook.OrderbookSnapshot0\x01\x12L\n\x0cGetOrderbook\x12\x1e.orderbook.GetOrderbookRequest\x1a\x1c.orderbook.OrderbookSnapshot\x12I\n\nGetMarkets\x12\x1c.orderbook.GetMarketsRequest\x1a\x1d.orderbook.GetMarketsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=30
  _globals['_SUBSCRIBEREQUEST']._serialized_end=111
  _globals['_GETORDERBOOKREQUEST']._serialized_start=113
  _globals['_GETORDERBOOKREQUEST']._serialized_end=168
  _globals['_GETMARKETSREQUEST']._serialized_start=170
  _globals['_GETMARKETSREQUEST']._serialized_end=189
  _globals['_GETMARKETSRESPONSE']._serialized_start=191
  _globals['_GETMARKETSRESPONSE']._serialized_end=251
  _globals['_MARKETINFO']._serialized_start=253
  _globals['_MARKETINFO']._serialized_end=316
  _globals['_ORDERBOOKSNAPSHOT']._serialized_start=319
  _globals['_ORDERBOOKSNAPSHOT']._serialized_end=487
  _globals['_PRICELEVEL']._serialized_start=489
  _globals['_PRICELEVEL']._serialized_end=555
  _globals['_ORDER']._serialized_start=557
  _globals['_ORDER']._serialized_end=649
  _globals['_ORDERBOOKSERVICE']._serialized_start=652
  _globals['_ORDERBOOKSERVICE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
